# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            missuteki
tagline:          'missuteki, make mistakes'
description:      'Engrish for "mistake" and japanese for "three awesome". This is a blog of my artwork done in triplicate. '
url:              http://missuteki.com
baseurl:          
commentsystem:    disqus
disqus:           missuteki

author:
  name:           Ariel Liu
  url:            http://www.helloarielliu.com/

paginate:         5

# Custom vars
icon:             /assets/images/missuteki-logo.png
cover:            

social:
  - icon:         twitter
    url:          https://twitter.com/missuteki
    desc:         Follow me on twitter

  - icon:         feed
    url:          http://missuteki.com/atom.xml
    desc:         Subscribe to my feed

menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

copyright:
  author:         missuteki
  url:            http://missuteki.com
  type_title:     Theme based on Thinny
  type_url:       https://github.com/camporez/Thinny

parallax:         true

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  UA-98291737-1

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576

# Gems
gems: [jekyll-paginate]